Upgrade default value for Node_ENV
Due to update production don't work anymore

Error: invalid environment: "production"
    at initFeatureFlags (/home/blaze/near-contract-helper/node_modules/@near-wallet/feature-flags/src/index.js:7:15)
    at Object.<anonymous> (/home/blaze/near-contract-helper/features/features.js:6:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/blaze/near-contract-helper/features/index.js:1:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
Program node app exited with code 1